version: "3.9"
services:

  mysql8:
    container_name: mysql8
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SoyelN1delMus!
      MYSQL_DATABASE: users
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres15:
    container_name: postgres15
    image: postgres:15-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: SoyelN1delMus!
      POSTGRES_DB: labs
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  users:
    container_name: users
    image: gontorres26/users
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: users
      DB_USERNAME: root
      DB_PASSWORD: SoyelN1delMus!
      LABS_URL: labs:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  labs:
    container_name: labs
    image: gontorres26/labs
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres15:5432
      DB_DATABASE: labs
      DB_USERNAME: postgres
      DB_PASSWORD: SoyelN1delMus!
      USERS_URL: users:8001
    networks:
      - spring
    depends_on:
      - postgres15
      - users
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring