apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: gontorres26/users:latest
          ports:
            - containerPort: 8001
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: users
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: users
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: users
                  key: db_database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: users
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users
                  key: db_password
            - name: LABS_URL
              valueFrom:
                configMapKeyRef:
                  name: users
                  key: labs_url