apiVersion: apps/v1
kind: Deployment
metadata:
  name: labs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labs
  template:
    metadata:
      labels:
        app: labs
    spec:
      containers:
        - name: labs
          image: gontorres26/labs:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: labs
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: labs
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: labs
                  key: db_database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: labs
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: labs
                  key: db_password
            - name: USERS_URL
              valueFrom:
                configMapKeyRef:
                  name: labs
                  key: users_url